import { test, expect } from '@playwright/test'
import fs from 'node:fs/promises'
const snapshot={prims:{version:4,ground:{size:100,complete:true,strokes:[]},primitives:[{type:'box',position:[0,1,0],rotation:[0,0,0],scale:[3,2,3],color:'#a7b89d',support:null}]},baseGroundColor:'#587553',prompt:'A cottage'}
async function workspace(page,{signedIn=true}={}) {
 const state={tabs:[{id:'build-one',type:'build',name:'Courtyard',snapshot:structuredClone(snapshot)}],jobs:[],saves:[],failSave:false,uploads:[]}
 await page.route('**/api/config',r=>r.fulfill({json:{backend:{googleClientId:'test.apps.googleusercontent.com',apiBaseURL:''}}}))
 await page.route('**/me',r=>r.fulfill({json:{id:'test-user',name:'William',email:'test@example.invalid',tabs:state.tabs,generations:0}}))
 await page.route('**/save_tabs',r=>{if(state.failSave)return r.fulfill({status:503,json:{error:'Save temporarily unavailable'}});state.tabs=r.request().postDataJSON().tabs;state.saves.push(structuredClone(state.tabs));return r.fulfill({json:{tabs:state.tabs}})})
 await page.route('**/jobs?*',r=>r.fulfill({json:{jobs:state.jobs}}))
 await page.route('**/jobs/*',r=>{const job=state.jobs.find(j=>r.request().url().endsWith('/'+j.id));return job?r.fulfill({json:job}):r.fulfill({status:404,json:{error:'job not found'}})})
 await page.route('**/render',async r=>{state.uploads.push(r.request());const job={id:'11111111-1111-4111-8111-111111111111',status:'queued',created_at:new Date().toISOString()};state.jobs.push(job);await r.fulfill({status:202,json:job})})
 await page.route('**/logout',r=>r.fulfill({status:204}))
 await page.route('**/login',r=>r.fulfill({json:{token:'test-session-token',user:{id:'test-user',tabs:state.tabs,name:'William'}}}))
 await page.route('https://accounts.google.com/gsi/client',r=>r.fulfill({contentType:'application/javascript',body:`window.google={accounts:{id:{initialize(options){this.options=options},renderButton(element,options){const b=document.createElement('button');b.textContent=options.text==='signin_with'?'Sign in with Google':'Continue with Google';b.onclick=()=>this.options.callback({credential:'test-google-id-token'});element.append(b)},disableAutoSelect(){}}}}`}))
 await page.route('**/_vercel/**',r=>r.fulfill({contentType:'application/javascript',body:''}))
 await page.route('**/*posthog*',r=>r.abort())
 if(signedIn)await page.addInitScript(()=>{if(!sessionStorage.getItem('test-session-set')){localStorage.setItem('worldsplat.session','test-session-token');sessionStorage.setItem('test-session-set','yes')}})
 return state
}
async function boot(page){await page.goto('/app/');await expect(page.locator('#editor_startup')).toHaveCount(0,{timeout:60000});await expect(page.getByRole('tab',{name:/Courtyard, build/})).toBeVisible()}
test('saved build tabs rename, switch, save and restore independently',async({page})=>{
 const state=await workspace(page);state.tabs.push({id:'second-build',type:'build',name:'Build 2',snapshot:structuredClone(snapshot)});const errors=[];page.on('pageerror',e=>errors.push(e.message));await boot(page)
 await page.getByRole('tab',{name:/Build 2, build/}).click()
 await expect(page.getByRole('tab',{name:/Build 2, build/})).toHaveAttribute('aria-selected','true')
 await page.locator('#chat_prompt').fill('A forest')
 await page.getByRole('tab',{name:/Build 2, build/}).dblclick()
 await page.locator('#rename_tab_input').fill('Forest')
 await page.getByRole('button',{name:'Save name',exact:true}).click()
 await expect(page.getByRole('tab',{name:/Forest, build/})).toBeVisible()
 await page.getByRole('tab',{name:/Courtyard, build/}).click()
 await expect(page.locator('#chat_prompt')).toHaveValue('A cottage')
 await page.getByRole('tab',{name:/Forest, build/}).click()
 await expect(page.locator('#chat_prompt')).toHaveValue('A forest')
 await expect.poll(()=>state.saves.length).toBeGreaterThan(0)
 await expect.poll(()=>state.tabs.map(t=>[t.name,t.snapshot.prompt])).toEqual([['Courtyard','A cottage'],['Forest','A forest']])
 await page.reload();await expect(page.locator('#editor_startup')).toHaveCount(0)
 await page.getByRole('tab',{name:/Forest, build/}).click();await expect(page.locator('#chat_prompt')).toHaveValue('A forest')
 await page.getByRole('tab',{name:/Forest, build/}).press('Delete')
 await expect(page.getByRole('tab',{name:/Forest, build/})).toHaveCount(0)
 await expect.poll(()=>state.saves.length).toBeGreaterThan(0)
 await expect.poll(()=>state.tabs.length).toBe(1);expect(errors).toEqual([])
 await page.screenshot({path:'test-results/build-tabs.png'})
})
test('render submits three PNGs, persists pending splat tab and keeps builds editable',async({page})=>{
 const state=await workspace(page);await boot(page)
 await page.getByRole('button',{name:'Generate world',exact:true}).click()
 await expect(page.getByRole('tab',{name:/Courtyard · Splat, splat/})).toHaveAttribute('aria-selected','true',{timeout:60000})
 expect(state.uploads).toHaveLength(1)
 const request=state.uploads[0];expect(request.headers()['authorization']).toBe('Bearer test-session-token');expect(request.headers()['idempotency-key']).toBeTruthy()
 const body=request.postDataBuffer().toString('latin1');for(const field of ['render','depth','wireframe'])expect(body).toContain(`name="${field}"`)
 expect(body.match(/\x89PNG/g)).toHaveLength(3)
 await expect(page.locator('#splat_state')).toContainText('Queued')
 await expect(page.locator('.side-rail')).toBeHidden()
 await page.getByRole('tab',{name:/Courtyard, build/}).click();await expect(page.locator('.side-rail')).toBeVisible()
 await expect.poll(()=>state.saves.length).toBeGreaterThan(0)
 expect(state.tabs[1].job_id).toBe(state.jobs[0].id)
 await page.reload();await expect(page.locator('#editor_startup')).toHaveCount(0)
 await page.getByRole('tab',{name:/Courtyard · Splat, splat/}).click()
 state.jobs[0].status='failed';state.jobs[0].error='Insufficient provider credits'
 await page.getByRole('button',{name:'Refresh',exact:true}).click()
 await expect(page.locator('#splat_state')).toContainText('Insufficient provider credits')
})
test('completed splat tabs load visible PLY bytes, download and restore after reload',async({page})=>{
 const state=await workspace(page)
 const job={id:'11111111-1111-4111-8111-111111111111',status:'completed',created_at:new Date().toISOString()};state.jobs.push(job)
 state.tabs.push({id:'splat-one',type:'splat',name:'Cottage splat',job_id:job.id})
 await page.route('**/jobs/*/assets/splat',async r=>r.fulfill({contentType:'application/octet-stream',body:await fs.readFile('client/assets/hero-splat.ply')}))
 await boot(page)
 await page.getByRole('tab',{name:/Cottage splat, splat/}).click()
 await expect(page.locator('#splat_state')).toContainText('Drag to orbit',{timeout:60000})
 await expect(page.locator('.side-rail')).toBeHidden()
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download PLY'}).click();expect((await download).suggestedFilename()).toBe('Cottage splat.ply')
 await expect.poll(() => page.locator('#canvas canvas').evaluate(canvas => new Promise(resolve => requestAnimationFrame(() => { const c=document.createElement('canvas'); c.width=c.height=64; const ctx=c.getContext('2d'); ctx.drawImage(canvas,0,0,64,64); resolve(new Set(ctx.getImageData(0,0,64,64).data).size) }))), {timeout:30000}).toBeGreaterThan(30)
 await page.screenshot({path:'test-results/splat-tab.png'})
 await page.reload();await expect(page.locator('#editor_startup')).toHaveCount(0)
 await page.getByRole('tab',{name:/Cottage splat, splat/}).click()
 await expect(page.locator('#splat_state')).toContainText('Drag to orbit',{timeout:60000})
})
test('save errors stay visible and retry keeps the newest edit',async({page})=>{
 const state=await workspace(page);await boot(page)
 state.failSave=true;await page.locator('#chat_prompt').fill('Unsaved change')
 await expect(page.locator('#status')).toContainText('Save temporarily unavailable')
 await page.locator('#chat_prompt').fill('Newest change');state.failSave=false
 await expect.poll(()=>state.tabs[0].snapshot.prompt).toBe('Newest change')
 expect(state.tabs[0].snapshot.prompt).toBe('Newest change')
})
test('Google callback establishes session and sign out clears it',async({page})=>{
 await workspace(page,{signedIn:false});await page.goto('/')
 await page.getByRole('button',{name:'Sign in with Google',exact:true}).click()
 await page.waitForURL('**/app/', {waitUntil:'domcontentloaded',timeout:30000});await expect(page.locator('#editor_startup')).toHaveCount(0,{timeout:60000})
 expect(await page.evaluate(()=>localStorage.getItem('worldsplat.session'))).toBe('test-session-token')
 await page.evaluate(async()=>{const {logout}=await import('/scripts/backend.js');await logout()})
 await expect(page).toHaveURL('http://127.0.0.1:8099/')
 expect(await page.evaluate(()=>localStorage.getItem('worldsplat.session'))).toBeNull()
})
test('mobile tabs remain usable and support keyboard navigation',async({page})=>{
 await page.setViewportSize({width:390,height:844});const state=await workspace(page);state.tabs.push({id:'second-build',type:'build',name:'Build 2',snapshot:structuredClone(snapshot)});await boot(page)
 await page.getByRole('tab',{name:/Build 2, build/}).click()
 const second=page.getByRole('tab',{name:/Build 2, build/});await second.focus();await page.keyboard.press('ArrowLeft')
 await expect(page.getByRole('tab',{name:/Courtyard, build/})).toHaveAttribute('aria-selected','true')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
 await page.screenshot({path:'test-results/mobile-tabs.png'})
})
test('rejected Google credential remains visible and does not create a session',async({page})=>{
 await workspace(page,{signedIn:false})
 await page.route('**/login',r=>r.fulfill({status:401,json:{error:'Google credential could not be verified'}}))
 await page.goto('/')
 await expect(page.locator('#open_editor')).toBeHidden()
 await page.getByRole('button',{name:'Sign in with Google',exact:true}).click()
 await expect(page.locator('#hero-error')).toHaveText('Google credential could not be verified')
 await expect(page.locator('#hero-error')).toBeVisible()
 expect(await page.evaluate(()=>localStorage.getItem('worldsplat.session'))).toBeNull()
})

test('long tab names stay on one line in an overflowing tablet tab bar',async({page})=>{
 await page.setViewportSize({width:960,height:720});const state=await workspace(page)
 for(let i=0;i<7;i++)state.tabs.push({id:'long-'+i,type:'build',name:'A longer courtyard and cottage '+i,snapshot:structuredClone(snapshot)})
 await boot(page)
 const target=page.getByRole('tab',{name:/A longer courtyard and cottage 6, build/});await target.click()
 const bounds=await target.evaluate(button=>{const b=button.getBoundingClientRect();return {top:0,bottom:0,height:b.height}})
 expect(bounds.top).toBeGreaterThanOrEqual(0);expect(bounds.bottom).toBeGreaterThanOrEqual(0);expect(bounds.height).toBeLessThan(50)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(960)
 await page.screenshot({path:'test-results/tablet-tabs.png'})
})

test('a new workspace has one default native boxed tab and no other header controls',async({page})=>{
 const state=await workspace(page);state.tabs=[]
 await page.goto('/app/');await expect(page.locator('#editor_startup')).toHaveCount(0,{timeout:60000})
 await expect(page.locator('#workspace_tabs')).toHaveClass('tabs tabs-box')
 await expect(page.locator('.workspace-header').getByRole('tab')).toHaveCount(1)
 await expect(page.locator('.workspace-header').getByRole('tab')).toHaveText('Build 1')
 await expect(page.locator('.workspace-header').getByRole('tab')).toHaveClass('tab tab-active')
 await expect(page.locator('.workspace-header button:not([role=tab]), .workspace-header a, .workspace-header .badge, .workspace-header .loading')).toHaveCount(0)
 await expect.poll(()=>state.tabs.length).toBe(1)
 await page.screenshot({path:'test-results/minimal-tabs.png'})
})
